image: gitpod/workspace-full

vscode:
  extensions:
    - octref.vetur@0.23.0:TEzauMObB6f3i2JqlvrOpA==

tasks:
  - init: >
      touch /tmp/.npm-lock &&
      npm install &&
      npm install -g @vue/cli &&
      npm install -g json-server &&
      rm /tmp/.npm-lock
    command:
      npm run serve
  - init: sleep 1 && while [ -f /tmp/.npm-lock ]; do sleep 2; done
    command: json-server db.json