image: gitpod/workspace-full

vscode:
  extensions:
    - octref.vetur@0.23.0:TEzauMObB6f3i2JqlvrOpA==

tasks:
  - init: >
      touch /tmp/.npm-lock-npm &&
      touch /tmp/.npm-lock-db &&
      npm install &&
      rm /tmp/.npm-lock-npm
    command:
      npm run serve
  
  - init: sleep 1 && while [ -f /tmp/.npm-lock-npm ]; do sleep 2; done
    command: npm install -g @vue/cli
  
  - init: sleep 1 && while [ -f /tmp/.npm-lock-npm ]; do sleep 2; done
    command: npm install --save axios

  - init: sleep 1 && while [ -f /tmp/.npm-lock-npm ]; do sleep 2; done
    command: >
          npm install -g json-server &&
          json-server db.json

  - command: gp await-port 3000 && gp preview $(gp url 3000)/todos

ports:
  - port: 8080
    onOpen: open-browser
